### ISSUE TITLE
private method `gsub' called for nil:NilClass

### ISSUE THREAD

**Issue by fanday** [alno/irwi#24]
enviroment:
rails 3.0.5
irwi (0.4.1)
actionpack (>= 3.0.0)
activerecord (>= 3.0.0)
activesupport (>= 3.0.0)
diff-lcs (>= 1.1.2)

I have installed irwi and generated irwi_wiki, everything seems OK.But  after DB migrate,I run my app,and visit wiki, then got this error.

rails error info in chrome:
NoMethodError in Wiki_pages#show

Showing /home/fanday/.bundler/ruby/1.8/irwi-3cfb6f192e2d/app/views/base_wiki_pages/no.html.erb where line #1 raised:

private method `gsub' called for nil:NilClass
Extracted source (around line #1):

1: <%=(wt 'There is no such page. Do you want to <a href="%{new_url}">create it</a>?', :new_url => wiki_page_new_path ).html_safe %>  

thanks very much.

**Comment by alno** [comment]
Fixed by now
