### ISSUE TITLE
edit.html.erb doesn't render correctlywith application.html.haml

### ISSUE THREAD

**Issue by toddh** [alno/irwi#28]
Right of the box, I seem to see a problem with edit.  The generated HTML looks like this:

```
<p>Content:<br />&lt;textarea cols=&quot;40&quot; id=&quot;page_content&quot; name=&quot;page[content]&quot; rows=&quot;20&quot;&gt;FAQs Here!&lt;/textarea&gt;</p>
```

Notice the beginning of the input tag is missing and then the HTML is quoted.  The other fields do render correctly.

I'm using HAML and my application layout file is in HAML.  When I convert edit.html.erb to edit.html.haml and place it in my applications view/wiki_pages folder, all seems to be good.

This leads me to think that there's a mismatch somewhere between erb and haml.  This might not be an irwi problem but that's where I encountered it.  Thought I'd let you know.

**Comment by alno** [comment]
With current versions of haml and irwi problem is fixed.
