### ISSUE TITLE
rails4 couldn't execute 'rails g irwi_wiki'

### ISSUE THREAD

**Issue by shtoma** [alno/irwi#35]
Hi. I'm beginner of irwi.
In my sample app, ruby2 with rails4, failed the rails generate command.

$ ../rails/railties/bin/rails g irwi_wiki
/usr/local/www/codes/rails4/rails/activesupport/lib/active_support/dependencies.rb:228:in `require': cannot load such file -- rails/generators/active_record/migration (LoadError)

Is it fixeable?

**Comment by alno** [comment]
Fixed in 0.5.0
