### ISSUE TITLE
cannot load such file -- redcloth

### ISSUE THREAD

**Issue by matt-doeringtech** [alno/irwi#36]
This is a new project with:

ruby 1.9.3p194 (2012-04-20 revision 35410)
Rails 3.2.9

The gem file has, among others:
gem 'irwi', :git => 'git://github.com/alno/irwi.git' 
gem 'haml-rails'

I added the gem, did the migration and then tried to create the first page.  The editor came up just fine but then when I tried to save I got:

=========================================
ActionView::Template::Error (cannot load such file -- redcloth):
    6: <%= wiki_page_actions %>
    7:   
    8: <div class="wiki_content">
    9:   <%=wiki_content @page.content %>
    10: </div>
  activesupport (3.2.9) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.9) lib/active_support/dependencies.rb:251:in `block in require'
  activesupport (3.2.9) lib/active_support/dependencies.rb:236:in `load_dependency'
  activesupport (3.2.9) lib/active_support/dependencies.rb:251:in `require'
  /home/mdoering/.rvm/gems/ruby-1.9.3-p194/bundler/gems/irwi-df0c21c14b33/lib/irwi/formatters/red_cloth.rb:4:in `initialize'
  /home/mdoering/.rvm/gems/ruby-1.9.3-p194/bundler/gems/irwi-df0c21c14b33/lib/irwi/config.rb:19:in `new'
  /home/mdoering/.rvm/gems/ruby-1.9.3-p194/bundler/gems/irwi-df0c21c14b33/lib/irwi/config.rb:19:in `formatter'
  /home/mdoering/.rvm/gems/ruby-1.9.3-p194/bundler/gems/irwi-df0c21c14b33/lib/irwi/helpers/wiki_pages_helper.rb:42:in `wiki_content'

=========================================

It looks like redcloth is not happy with the erb file?  Any thoughts?

Thank you

**Comment by alno** [comment]
Rewrited README section so it should be more clear. Also, now (still on master) formatter is automatically detected based on gems loaded.
