### ISSUE TITLE
ActiveModel::MassAssignmentSecurity::Error in WikiPagesController#add_attachment

### ISSUE THREAD

**Issue by Lapizistik** [alno/irwi#37]
Hi,
I currently try to use irwi attachments and get the following error:
> ActiveModel::MassAssignmentSecurity::Error in WikiPagesController#add_attachment
> Can't mass-assign protected attributes: wiki_page_attachment, page_id
in
> irwi-df0c21c14b33/lib/irwi/extensions/controllers/wiki_page_attachments.rb:4:in `new'
> irwi-df0c21c14b33/lib/irwi/extensions/controllers/wiki_page_attachments.rb:4:in `add_attachment'

Because of issue #31 i switched from the gem on rubygems to the git version:
Gemfile:
> gem "irwi", :git => "git://github.com/alno/irwi.git"
> gem 'paperclip'

Running Debian stable with
> ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-linux]
> Rails 3.2.5

**Comment by alno** [comment]
Fixed in 0.5.0

**Comment by Lapizistik** [comment]
Thanks for your work!
